# Generated by Django 5.1.1 on 2025-04-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_types",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Like"),
                    (2, "Comment"),
                    (3, "Follow"),
                    (4, "Message"),
                    (5, "Dislike"),
                ],
                null=True,
            ),
        ),
    ]
