# Generated by Django 5.1.1 on 2025-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0002_alter_notification_post_alter_notification_sender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_types",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Like"), (2, "Comment"), (3, "Follow"), (4, "Message")],
                null=True,
            ),
        ),
    ]
