# Generated by Django 5.0.7 on 2024-09-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_itemmessage_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
