# Generated by Django 5.1.1 on 2024-10-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_conversation_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmessage',
            old_name='message',
            new_name='item_message',
        ),
    ]
