# Generated by Django 5.1.1 on 2024-10-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_itemmessage_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmessage',
            old_name='receiver',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='itemmessage',
            old_name='sender',
            new_name='sender_name',
        ),
    ]
