# Generated by Django 5.1.1 on 2024-10-11 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_rename_receiver_itemmessage_receiver_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
