# Generated by Django 5.1.1 on 2024-10-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_item_date_sold_remove_item_is_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmessage',
            old_name='item_message',
            new_name='message',
        ),
    ]
