# Generated by Django 5.1.1 on 2024-10-17 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_room_item_room_item_id'),
        ('marketplace', '0011_rename_message_itemmessage_item_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='itemmessage',
            old_name='item_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='itemmessage',
            name='item_sender',
        ),
        migrations.AddField(
            model_name='itemmessage',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='itemmessage',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
