# Generated by Django 5.1.1 on 2024-10-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_is_private_room_participants'),
        ('marketplace', '0012_alter_itemmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
