# Generated by Django 5.0.7 on 2024-08-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_blog_author',
        ),
    ]
