# Generated by Django 5.0.7 on 2024-09-23 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_userprofile_is_blog_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='ItemMessage',
        ),
    ]
