# Generated by Django 5.1.1 on 2024-10-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('marketplace', '0011_rename_message_itemmessage_item_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='marketplace.item'),
        ),
    ]
