# Generated by Django 5.1.1 on 2025-03-28 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_receiver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="participants",
            new_name="participant",
        ),
    ]
