# Generated by Django 5.1.1 on 2024-10-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_date_alter_message_sender_itemroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemroom',
            name='itemroom_name',
        ),
    ]
