# Generated by Django 5.1.1 on 2024-10-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_item'),
        ('marketplace', '0011_rename_message_itemmessage_item_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='item',
        ),
        migrations.AddField(
            model_name='room',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.item'),
        ),
    ]
