# Generated by Django 5.1.1 on 2024-10-11 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_itemroom_itemroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
