# Generated by Django 5.0.7 on 2024-09-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='item_message',
        ),
    ]
