# Generated by Django 5.1.1 on 2024-10-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_itemroom_item'),
        ('marketplace', '0010_alter_itemmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemroom',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='marketplace.item'),
        ),
    ]
