# Generated by Django 5.1.1 on 2024-10-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_itemroom_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacemessage',
            name='item_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_room_id', to='chat.itemroom'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
