# Generated by Django 5.1.1 on 2024-10-12 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_tag_name_alter_tag_slug'),
        ('chat', '0008_alter_marketplacemessage_item_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.room')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to='blog.profile')),
            ],
            bases=('chat.room',),
        ),
    ]
