# Generated by Django 5.1.1 on 2024-10-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_creator'),
        ('marketplace', '0011_rename_message_itemmessage_item_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemroom',
            name='item',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='marketplace.item'),
        ),
    ]
