# Generated by Django 5.1.1 on 2024-10-14 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_itemroom_seller'),
        ('marketplace', '0011_rename_message_itemmessage_item_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemroom',
            name='item',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='marketplace.item'),
        ),
        migrations.AlterField(
            model_name='itemroom',
            name='seller',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
