# Generated by Django 5.1.1 on 2025-04-08 19:34

import blog.fields
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=blog.fields.SVGAndImageField(
                default="",
                upload_to=blog.models.user_directory_path,
                validators=[
                    blog.fields.validate_svg_or_image,
                    blog.fields.validate_svg_or_image,
                ],
                verbose_name="Picture",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="verification_score",
            field=models.FloatField(
                default=1, help_text="Post verification score based on polls (0.0-1.0)"
            ),
        ),
    ]
