# Generated by Django 5.1.1 on 2025-04-11 19:41

import blog.fields
import blog.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_likes_like_alter_post_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=blog.fields.SVGAndImageField(
                default="",
                upload_to=blog.models.user_directory_path,
                validators=[
                    blog.fields.validate_svg_or_image,
                    blog.fields.validate_svg_or_image,
                ],
                verbose_name="Picture",
            ),
        ),
    ]
