# Generated by Django 5.1 on 2024-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_user_stream_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Video'),
        ),
    ]
