# Generated by Django 5.1 on 2024-08-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_video'),
        ('blog', '0016_remove_post_tags_alter_post_video_delete_stream_and_more'),
    ]

    operations = [
    ]
