# Generated by Django 5.0.7 on 2024-09-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
