# Generated by Django 5.0.7 on 2024-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stream',
            field=models.CharField(blank=True, default='Post', max_length=200),
        ),
    ]
