# Generated by Django 5.1.1 on 2025-03-30 19:02

import blog.fields
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0033_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="verification_score",
            field=models.FloatField(
                default=0.5,
                help_text="Post verification score based on polls (0.0-1.0)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="credibility_score",
            field=models.FloatField(
                default=0.5,
                help_text="Author credibility score based on verification polls (0.0-1.0)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_history",
            field=models.JSONField(
                default=list, help_text="History of verification poll results"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=blog.fields.SVGAndImageField(
                default="",
                upload_to=blog.models.user_directory_path,
                validators=[
                    blog.fields.validate_svg_or_image,
                    blog.fields.validate_svg_or_image,
                ],
                verbose_name="Picture",
            ),
        ),
    ]
