# Generated by Django 5.1.1 on 2025-03-30 19:38

import blog.fields
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0034_post_verification_score_profile_credibility_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="verification_details",
            field=models.JSONField(
                default=dict, help_text="Detailed verification results from polls"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("disputed", "Disputed"),
                    ("warning", "Needs Clarification"),
                    ("mixed", "Mixed Verification"),
                ],
                default="unverified",
                help_text="Current verification status of the post",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="credibility_breakdown",
            field=models.JSONField(
                default=dict, help_text="Category-specific credibility scores"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_trend",
            field=models.FloatField(
                default=0.0,
                help_text="Trend in verification scores over time (-1.0 to 1.0)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=blog.fields.SVGAndImageField(
                default="",
                upload_to=blog.models.user_directory_path,
                validators=[
                    blog.fields.validate_svg_or_image,
                    blog.fields.validate_svg_or_image,
                ],
                verbose_name="Picture",
            ),
        ),
    ]
