# Generated by Django 5.1.1 on 2025-04-03 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Poll"),
                            ("verification", "Author Verification"),
                            ("source_check", "Source Verification"),
                            ("fact_check", "Fact Accuracy"),
                            ("argument_quality", "Argument Quality"),
                            ("expertise_check", "Author Expertise"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "verification_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight of this question in verification scoring",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related blog post for post-specific questions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="blog.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "verification_impact",
                    models.CharField(
                        choices=[
                            ("positive", "Positive Verification"),
                            ("negative", "Negative Verification"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        help_text="Impact on verification score for verification questions",
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight of this choice in verification scoring",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this vote was from a verified user",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.choice"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="voters",
            field=models.ManyToManyField(
                blank=True, through="polls.VoteRecord", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["question", "user"], name="polls_voter_questio_9d81a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["user", "voted_at"], name="polls_voter_user_id_381c49_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together={("user", "question")},
        ),
    ]
