# Generated by Django 5.1.1 on 2025-03-30 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0035_post_verification_details_post_verification_status_and_more"),
        ("polls", "0002_question_post_question_question_type_voterecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="verification_impact",
            field=models.CharField(
                choices=[
                    ("positive", "Positive Verification"),
                    ("negative", "Negative Verification"),
                    ("neutral", "Neutral"),
                ],
                default="neutral",
                help_text="Impact on verification score for verification questions",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="weight",
            field=models.FloatField(
                default=1.0, help_text="Weight of this choice in verification scoring"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="verification_weight",
            field=models.FloatField(
                default=1.0, help_text="Weight of this question in verification scoring"
            ),
        ),
        migrations.AddField(
            model_name="voterecord",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Whether this vote was from a verified user"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="Related blog post for post-specific questions",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Poll"),
                    ("verification", "Author Verification"),
                    ("source_check", "Source Verification"),
                    ("fact_check", "Fact Accuracy"),
                    ("argument_quality", "Argument Quality"),
                    ("expertise_check", "Author Expertise"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["question", "user"], name="polls_voter_questio_9d81a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voterecord",
            index=models.Index(
                fields=["user", "voted_at"], name="polls_voter_user_id_381c49_idx"
            ),
        ),
    ]
