# Generated by Django 5.1.1 on 2025-04-08 18:13

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for hash table lookup"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("date_indexed", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "numeric_field",
                    models.FloatField(
                        blank=True,
                        help_text="For binary search on numeric values",
                        null=True,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="search_sear_content_97a989_idx",
                    ),
                    models.Index(fields=["title"], name="search_sear_title_51a3a1_idx"),
                    models.Index(
                        fields=["author"], name="search_sear_author__c9b2ff_idx"
                    ),
                    models.Index(
                        fields=["date_indexed"], name="search_sear_date_in_8beee3_idx"
                    ),
                    models.Index(
                        fields=["category"], name="search_sear_categor_dc6fcb_idx"
                    ),
                ],
            },
        ),
    ]
